### ISSUE TITLE
how about adding event delegate

### ISSUE THREAD

**Issue by luckydrq** [tj/node-delegates#11]
I've been using nodejs for not a short time. In some of my projects, i need `events` bubbled from inside object. Here is a simple demo:
```js
const EventEmitter = require('events');

class A extends EventEmitter {
  constructor(options) {
    super(options);

    this._b = new B();
    this._b
      .on('ready', () => this.emit('ready'))
      .on('refresh', () => this.emit('refresh'))
      .on('error', err => this.emit('error', err));
  }
}

class B extends EventEmitter {
  constructor() {
    super();
  }

  init() {
    // do init stuff
    this.emit('ready');
  }

  refresh() {
    // do refresh
    this.emit('refresh');
  }
}

const a = new A();
a.on('error', err => {
  // handle error logic
});
```
I think the event binding code in constructor of A is ugly. Maybe we can use in a more elegant way. How about this:
```js
const delegate = require('delegates');
delegate(a, '_b')
  .event('ready')
  .event('refresh')
  .event('error');
```
yes it's just adding a `.event` api. So if it makes sense, i am glad to submit a PR.

**Comment by tj** [comment]
I think in your example above you could do:

```js
this._b
  .on('ready', this.emit.bind('ready'))
  .on('refresh', this.emit.bind('refresh'))
  .on('error', this.emit.bind('error'))
```

which isn't too bad. I'd probably rather keep events out of here since it gets a bit more complicated, if people want to unbind some or all etc

**Comment by luckydrq** [comment]
alright, i've got the point.
